### PR TITLE
Add Italian localization

### PR DESCRIPTION
**Pull request by quazar-omega**
I just noticed that the commit messages are formatted in a specific way, do you want me to change them to fit with the rest?

By the way, I noticed some inconsistencies and little mistakes in the originals, are you interested in another pull request for that? (stuff like `wine → Wine`, stick to either of `edition/version` for certain phrases, `on → at` your own risk, etc.)

---
notes: 
- I haven't compiled to check how it looks in the actual application, should I do that first?
- I think it'd be nice to have "Contribute" and "Translate" sections in the readme to make it easier for us to know what to do

### CODE REVIEW

**Comment by quazar-omega** [comment]
Fixed the little oopsie (つ﹏<)

**Comment by cybik** [comment]
Grazie :D

**Comment by Mar0xy** [comment]
Can you squash all commits into one named `feat(i18n): Add italian localization`

**Comment by quazar-omega** [comment]
Of course, should I include the permission change too, or I can leave that on its own?

**Comment by quazar-omega** [comment]
I started another [pull request](https://github.com/an-anime-team/an-anime-game-launcher/pull/163), we can continue the discussion there

**Comment by Mar0xy** [comment]
> Of course, should I include the permission change too, or I can leave that on its own?

it's best to leave it as it doesn't really matter

**Pull request closed without merging**
