### PR TITLE
[translation-zhcn] update chinese translations

### PR DESCRIPTION
**Pull request by FeyXieXzf**

### CODE REVIEW

**Comment by Mar0xy** [comment]
Come on, Is it really **that** hard to submit the reviews?

image

**Comment by FeyXieXzf** [comment]
Sorry! Please forgive my ignorance - i really don't know that I have to *submit* the review so that the others can see them...Sorry...

**Comment by FeyXieXzf** [comment]
I haven't used the review function, so I don't really understand how to do it.

**Comment by FeyXieXzf** [comment]
bump

**Pull request merged**
