### PR TITLE
Support resuming pre-downloaded packages

### PR DESCRIPTION
**Pull request by tigersoldier**
* Check the size and MD5 checksum of the pre-downloaded packages
 * If the package is not fully downloaded, resume the download
 * If the downloaded package is too big or the MD5 checksum mismatches, remove it and re-download.

### CODE REVIEW

**Review by Mar0xy — APPROVED** [review]
This is a nice solution to an old problem that should have been fixed a long time ago but never was as this launcher sorta started being neglected after work on the GTK one began.

Just got to wait for Krypton's opinion on this.

**Comment by tigersoldier** [comment]
Just realized the previous patch will cause the predownloaded data being ignored because the `pre_download_data` is no longer populated when the game is officially released. Fixed now.

**Comment by tigersoldier** [comment]
@Mar0xy I like this version because it looks closer to the official launcher and the GTK version requires more space to install the game than this launcher. Also I don't know Rust so can only contribute to this launcher :P

@krypt0nn do you get a chance to look at this PR?

**Comment by krypt0nn** [comment]
Looks nice, will be merged. Thanks for your contribution

**Pull request merged**
