### PR TITLE
Fix applying voice predownloads and 3.4.0 voice update

### PR DESCRIPTION
**Pull request by tigersoldier**
The launcher failed to find the predownloaded voice pack due to checking for wrong version.

### CODE REVIEW

**Comment by tigersoldier** [comment]
Realized that there may still be bugs. Will mark it as ready when they are fixed.

**Comment by tigersoldier** [comment]
Turns out the bug was not caused by the predownload PR but hardcoding the .version file to 3.3.0. Fixed in this PR as well

**Comment by Mar0xy** [comment]
This issue could most likely be related to #50 and as such I will link them.

**Comment by krypt0nn** [comment]
image

Lmao I forgot to change this test code before making a commit
Thanks for your fix

**Pull request merged**
